version: "3.6"

services:
  pelican:
    build:
      context: ./pelican
    working_dir: /usr/src/app/volumes/pelican/output
    command: python -m pelican.server
    volumes:
      - ../:/usr/src/app
      - $GITHUB_SSH_PRIVATE_KEY/:/root/.ssh/id_rsa
      - $GITHUB_SSH_PUBLIC_KEY/:/root/.ssh/id_rsa.pub
    ports:
      - "8000:8000"

#  guard:
#    build: guard/
#    volumes:
#     - ../volumes/pelican:/usr/src/app
#    environment:
#      - RAILS_ENV=development
#    #entrypoint: ["tail", "-f", "/dev/null"]
#    command: bundle exec guard --no-bundler-warning --no-interactions
