version: "3.6"

services:
  pelican:
    build:
      context: ./pelican
    command: python -m pelican.server
    volumes:
     - ../volumes/pelican:/usr/src/app
    ports:
      - "8000:8000"

#  guard:
#    build: guard/
#    volumes:
#     - ../volumes/pelican:/usr/src/app
#    environment:
#      - RAILS_ENV=development
#    #entrypoint: ["tail", "-f", "/dev/null"]
#    command: bundle exec guard --no-bundler-warning --no-interactions
